server:
  port: 8088
  servlet:
    context-path: /recmv
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  #mvc:
    #view:
      #prefix: /WEB-INF/views/
      #suffix: .jsp
  mvc:
    converters:
      preferred-json-mapper: gson
      
  servlet:
    multipart:
      location: D:/summernote_image/
      
  thymeleaf:
    prefix: classpath:templates/thymeleaf/
    suffix: .html
     
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recmv?serverTimezone=Asia/Seoul
    username: chang
    password: chang1234
    
  #jpa:
    #open-in-view: true
    #hibernate:
      #ddl-auto: create
      #naming:
        #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #use-new-id-generator-mappings: false
    #show-sql: true
    #properties:
      #hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
      
mybatis:
  type-aliases-package: com.chang.recmv.model
  mapper-locations: mappers/**/*.xml